### PR TITLE
Reduce payload significantly by only requesting required fields.

### LINKED ISSUE #14: Limit fields in default field only to those required.
This only becomes an issue when you have hundreds of products, but we should be able to limit the default field to `id,title,variants` and have a much more performant default field with no drawbacks.

### PR DESCRIPTION
**Pull request by ryanpcmcquen**
Closes #14!

This cuts the payload almost in half. It makes a huge difference in load time when you have a lot of products.

Signed-off-by: Ryan McQuen <rmcquen@funko.com>

### CODE REVIEW

**Comment by nmaier95** [comment]
Hi @ryanpcmcquen I'll have a look at the weekend. Sorry for letting you wait.

**Comment by ryanpcmcquen** [comment]
@nmaier95, any chance to review this yet?

**Comment by ryanpcmcquen** [comment]
Thanks!

**Comment by nmaier95** [comment]
Appreciate your work!
It is now published with version 2.0.1

**Pull request merged**
