### PR TITLE
Feed Me support

### PR DESCRIPTION
**Pull request by elivz**
This PR adds support for importing Shopify product data using the [Feed Me](https://github.com/verbb/feed-me) plugin. The source data can contain either the product's title (must match exactly) or the Shopify product ID.

### CODE REVIEW

**Comment by nmaier95** [comment]
Thank you for your feedback!
Unfortunately I've been very busy lately. I'll have a look at your PR soon.

**Comment by nmaier95** [comment]
Hi @elivz, I don't see why this is needed for this plugin. This plugin pulls your shopify products again every time you are going to edit a page wich uses the product-field type. I admit this might not be the most performant way though. But the data is always as up to date as the shopify api returns it.

In general the use case seems to be too specific in my opinion.

**Comment by elivz** [comment]
I might not have explained this well enough. My PR doesn't enabled Feed Me to actually import the product data from Shopify into custom fields. Instead it allows you to import a CSV/JSON file with entry data, which includes a column containing either the Shopify product ID or the product title, and then it creates the associated inside of your fieldtype. So, for example, you could export a database of products from Shopify, and then import them using Feed Me to end up with an entry for each product, with the correct product preselected in the Product Fetcher field. 

Not sure if that changes your mind, and totally fine if not. Just wanted to make sure we are discussing the same thing!

**Comment by nmaier95** [comment]
closed due to inactivity.

**Pull request closed without merging**
